### ISSUE TITLE
ApplicationMaster out of memory?

### ISSUE THREAD

**Issue by gorlins** [blaze/rambling#112] opened 2017-11-02 02:18 UTC
I can't seem to start a cluster on elastic mapreduce from the head node - I think the ApplicationMaster is consuming too much vmem and being killed before the cluster can start.

Example:
    
    In [2]: knit.__version__
    Out[2]: '0.2.3'
    In [3]: cluster = DaskYARNCluster(packages=['python=3', 'numpy', 'pandas', 'dask', 'distributed'])
    In [4]: cluster.start()

Code thinks everything is working, but app logs suggest otherwise:

```
Application application_1509543030224_0006 failed 2 times due to AM Container for appattempt_1509543030224_0006_000002 exited with exitCode: -103
For more detailed output, check application tracking page:http://localhost:8088/cluster/app/application_1509543030224_0006Then, click on links to logs of each attempt.
Diagnostics: Container [pid=11934,containerID=container_1509543030224_0006_02_000001] is running beyond virtual memory limits. Current usage: 178.7 MB of 320 MB physical memory used; 2.0 GB of 1.6 GB virtual memory used. Killing container.
Dump of the process-tree for container_1509543030224_0006_02_000001 :
|- PID PPID PGRPID SESSID CMD_NAME USER_MODE_TIME(MILLIS) SYSTEM_TIME(MILLIS) VMEM_USAGE(BYTES) RSSMEM_USAGE(PAGES) FULL_CMD_LINE
|- 11934 11933 11934 11934 (bash) 0 0 115822592 678 /bin/bash -c /usr/lib/jvm/java-openjdk/bin/java -Xmx256M io.continuum.knit.ApplicationMaster 1>/var/log/hadoop-yarn/containers/application_1509543030224_0006/container_1509543030224_0006_02_000001/stdout 2>/var/log/hadoop-yarn/containers/application_1509543030224_0006/container_1509543030224_0006_02_000001/stderr
|- 11938 11934 11934 11934 (java) 464 26 2083704832 45057 /usr/lib/jvm/java-openjdk/bin/java -Xmx256M io.continuum.knit.ApplicationMaster
Container killed on request. Exit code is 143
Container exited with a non-zero exit code 143
Failing this attempt. Failing the application.
```

I think the relevant default params for EMR are here:
```
<property>
<name>yarn.scheduler.minimum-allocation-mb</name>
<value>32</value>
<source>java.io.BufferedInputStream@79e2c065</source>
</property>
<property>
<name>yarn.nodemanager.vmem-check-enabled</name>
<value>true</value>
<source>yarn-default.xml</source>
</property>
<property>
<name>yarn.nodemanager.vmem-pmem-ratio</name>
<value>5</value>
<source>java.io.BufferedInputStream@79e2c065</source>
</property>
```

And in Client.scala, the request for 300 mb memory producing - I assume - the 300 * 5 ~= 1.6gb vmem limit before killing the container.

I'm not sure if it's just python libs using up so much vmem, or something else...? I would suspect this isn't usually an issue since the default for `yarn.scheduler.minimum-allocation-mb` is 1024 and the request for 300mb is ignored, but in EMR this is lower for hbase I guess.

Thoughts?

**Comment by martindurant** [comment] 2017-11-02 13:58
`2.0 GB of 1.6 GB` does indeed sound incriminating.

As you can see, the applicationMaster does not in fact need even the 300MB requested for its container, and why the VM is so high is hard to understand (although there are suggestions [here](https://stackoverflow.com/a/33206213/3821154)). This is NOT down to anything in python, the applicationMaster is a pure-JVM process.

Nevertheless, you are right in suggesting that, with the minimum allocation typically 1024MB, the requirement could be made much higher. The relevant line is [this](https://github.com/dask/knit/blob/master/knit_jvm/src/main/scala/io/continuum/knit/Client.scala#L165) - you could edit and rebuild/reinstall to see if it works. 

If you administer your own cluster, then changing the values of `yarn.nodemanager.vmem-check-enabled` or `yarn.nodemanager.vmem-pmem-ratio` and restarting YARN may suffice.

**Comment by gorlins** [comment] 2017-11-06 14:32
I was able to get around this w/ additional configuration when starting EMR (changing config and restarting yarn did not work for some reason - possibly slave nodes were not properly restarted).  However, now I think I am running into #111 (exit status -1000, though I'm not having luck w/ v0.2.2 either).

**Comment by j-bennet** [comment] 2018-04-14 02:22
@gorlins I have the same problem - what additional configuration helped you?

**Comment by martindurant** [comment] 2018-04-14 02:56
@j-bennet , I presume he means the same variables I suggested in the above comment

**Comment by j-bennet** [comment] 2018-04-14 03:25
@martindurant But why is vmem so high in the first place? This does not seem right. I would rather fix the root cause than disable checks with `yarn.nodemanager.vmem-check-enabled`, or change ratio with `yarn.nodemanager.vmem-pmem-ratio`.

**Comment by martindurant** [comment] 2018-04-14 12:48
Well, the vmem is not memory really used at all, but memory that could potentially be required. The way I understand the linked explanation, this depends on the number of cores accessible on the machine (because java might conceivably run that many threads). It is wrong that java assumes this memory on initiation, and it is wrong of yarn to care about how much vmem a process reports, since this is not memory consumption at all - however, this is all beyond out control.

So the other fix is to up the amount of memory requested by knit to 1024, which is the usual minimum allocation in yarn. That won't change the vmem reported, and won't change the actual memory consumed by the process, but will make the vmem a smaller multiple of the memory request, thereby passing the yarn test.

**Comment by jcrist** [comment] 2018-07-03 18:24
dask-yarn has been rewritten, and should be more robust to different hadoop configurations. Please see the docs (https://dask-yarn.readthedocs.io/en/latest/) and new repo (https://github.com/dask/dask-yarn). Closing.

**Closed as completed by jcrist** 2018-07-03 18:24 UTC

**Comment by martindurant** [comment] 2018-07-03 18:26
@jcrist , it may be useful not to forget this one, as the confusion between real memory and process vmem may still occur.
